name: Build wheels
on: push
jobs:
  wheels-macos:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        brew install boost
    - name: Build QuantLib
      run: |
        tar xfz QuantLib-1.*.tar.gz
        cd QuantLib-1.*/
        ./configure --disable-shared --enable-unity-build --disable-test-suite
        make -j2 CXXFLAGS="-std=c++14 -g0 -O3 -fno-common -dynamic -DNDEBUG -fwrapv -arch ${{ matrix.arch }}" LDFLAGS="-fno-common -dynamic -DNDEBUG -fwrapv -arch ${{ matrix.arch }}"
        make install
    - name: Unpack QuantLib-SWIG
      run: |
        tar xfz QuantLib-SWIG-1.*.tar.gz
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        CXXFLAGS: -std=c++14 -g0 -O3
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-*/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-macos-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
  wheels-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: AMD64
            platform: x64
          - arch: x86
            platform: Win32
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.81.0/binaries/boost_1_81_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
    - name: Build QuantLib
      run: |
        Expand-Archive -Path QuantLib-1.30.zip -DestinationPath C:\local
        Copy-Item Build.props C:\local\QuantLib-1.30\
        Copy-Item Directory.Build.props C:\local\QuantLib-1.30\
        cd C:\local\QuantLib-1.30\
        msbuild QuantLib.vcxproj -p:Configuration="Release (static runtime)" -p:Platform=${{ matrix.platform }}
        dir lib
    - name: Unpack QuantLib-SWIG
      run: |
        Expand-Archive -Path QuantLib-SWIG-1.30.zip -DestinationPath .
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        QL_DIR: C:\local\QuantLib-1.30
        INCLUDE: C:\local\boost
        QL_STATIC_RUNTIME: 1
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-1.30/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-windows-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
  wheels-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686]
        image: [manylinux, musllinux]
    steps:
    - uses: actions/checkout@v3
    - name: Unpack QuantLib and QuantLib-SWIG
      run: |
        tar xfz QuantLib-1.*.tar.gz
        tar xfz QuantLib-SWIG-1.*.tar.gz
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: "*-${{ matrix.image }}*"
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.sh
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS=${{ matrix.arch == 'x86_64' && '"-O3 -g0"' || '"-O1 -g0"' }}
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: QuantLib-SWIG-1.*/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-${{ matrix.image }}-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
