name: Build wheels
on: push
jobs:
  wheels-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        brew install boost
    - name: Build QuantLib
      run: |
        tar xfz QuantLib-1.*.tar.gz
        cd QuantLib-1.*/
        ./configure --disable-shared --with-boost-include=`brew --prefix`/include --enable-unity-build --disable-test-suite --enable-skip-examples
        make -j3 CXXFLAGS="-std=c++14 -g0 -O3 -fno-common -dynamic -DNDEBUG -fwrapv" LDFLAGS="-fno-common -dynamic -DNDEBUG -fwrapv"
        sudo make install
    - name: Unpack QuantLib-SWIG
      run: |
        tar xfz QuantLib-SWIG-1.*.tar.gz
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.17.0
      env:
        CIBW_SKIP: cp36-* cp37-* pp37-* pp38-*
        CXXFLAGS: -std=c++14 -g0 -O3
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: ./QuantLib-SWIG-1.35/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl
  wheels-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: AMD64
            platform: x64
          - arch: x86
            platform: Win32
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.85.0/binaries/boost_1_85_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$RUNNER_TEMP\boost.exe")
        Start-Process -Wait -FilePath "$RUNNER_TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
    - name: Build QuantLib
      run: |
        Expand-Archive -Path QuantLib-1.35.zip -DestinationPath C:\local
        Copy-Item Build.props C:\local\QuantLib-1.35\
        Copy-Item Directory.Build.props C:\local\QuantLib-1.35\
        cd C:\local\QuantLib-1.35\
        msbuild QuantLib.vcxproj -p:Configuration="Release (static runtime)" -p:Platform=${{ matrix.platform }}
        dir lib
    - name: Unpack QuantLib-SWIG
      run: |
        Expand-Archive -Path QuantLib-SWIG-1.35.zip -DestinationPath .
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.17.0
      env:
        QL_DIR: C:\local\QuantLib-1.35
        INCLUDE: C:\local\boost
        QL_STATIC_RUNTIME: 1
        CIBW_SKIP: cp36-* cp37-* pp37-* pp38-*
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: ./QuantLib-SWIG-1.35/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-windows-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
  wheels-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, i686, aarch64]
        image: [manylinux, musllinux]
    steps:
    - uses: actions/checkout@v4
    - name: Unpack QuantLib and QuantLib-SWIG
      run: |
        tar xfz QuantLib-1.*.tar.gz
        tar xfz QuantLib-SWIG-1.*.tar.gz
    - name: Set up QEMU
      if: matrix.arch == 'aarch64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Build QuantLib wheels
      uses: pypa/cibuildwheel@v2.17.0
      env:
        CIBW_BUILD: "*-${{ matrix.image }}*"
        CIBW_SKIP: cp36-* cp37-* pp37-* pp38-*
        CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.sh
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS=${{ matrix.arch == 'x86_64' && '"-O3 -g0"' || '"-O0 -g0"' }} CXXQLFLAGS=${{ matrix.arch == 'aarch64' && '"-O2 -g0"' || '"-O3 -g0"' }}
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS CXXQLFLAGS
        CIBW_TEST_COMMAND: python {package}/test/QuantLibTestSuite.py
      with:
        package-dir: ./QuantLib-SWIG-1.35/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux-${{ matrix.image }}-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
  test-publish:
    runs-on: ubuntu-latest
    needs: [ wheels-macos, wheels-windows, wheels-linux ]
    environment: testpypi
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
    - name: Collect wheels
      run: |
        mkdir ./wheelhouse
        cp ./wheels-*/*.whl ./wheelhouse
        ls -l ./wheelhouse
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: ./wheelhouse
        skip-existing: true
  publish:
    runs-on: ubuntu-latest
    needs: test-publish
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
    - name: Collect wheels
      run: |
        mkdir ./wheelhouse
        cp ./wheels-*/*.whl ./wheelhouse
        ls -l ./wheelhouse
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./wheelhouse
        skip-existing: true
